version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: wallet-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: wallet-api
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/walletdb
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data:
